import React, { useState } from 'react';
import { Settings, Download, Trash2, CheckCircle, AlertCircle, Cpu, Zap, Link } from 'lucide-react';
import { motion } from 'framer-motion';
import { cn } from '../lib/utils';

type Mod = {
  id: string;
  name: string;
  version: string;
  author: string;
  status: 'Installed' | 'Enabled' | 'Disabled';
  description: string;
  aiEnhanced: boolean;
};

const initialMods: Mod[] = [
  { id: '1', name: 'Infinite AI Dialogue', version: '2.1.0', author: 'DeepSeeker', status: 'Enabled', description: 'Enables limitless neural conversation for all townspeople in Rattay.', aiEnhanced: true },
  { id: '2', name: 'Procedural Quest Engine', version: '1.0.4', author: 'NexusOne', status: 'Enabled', description: 'Adds dynamic side quests generated by Azure OpenAI backend.', aiEnhanced: true },
  { id: '3', name: 'Medieval Realistic Textures', version: '4.0.0', author: 'TextureKing', status: 'Disabled', description: '4K historically accurate texture overhaul.', aiEnhanced: false },
  { id: '4', name: 'Neural Alchemy Helper', version: '0.9.1', author: 'AlchemistAI', status: 'Installed', description: 'Real-time assistant for ingredient discovery during brewing.', aiEnhanced: true },
];

export default function ModManager() {
  const [mods, setMods] = useState<Mod[]>(initialMods);

  const toggleMod = (id: string) => {
    setMods(mods.map(m => {
      if (m.id === id) {
        return { ...m, status: m.status === 'Enabled' ? 'Disabled' : 'Enabled' };
      }
      return m;
    }));
  };

  return (
    <div className="space-y-12">
      <header className="flex justify-between items-end border-b-2 border-kcd-border pb-6">
        <div className="flex flex-col">
          <div className="flex items-center gap-2 mb-1">
            <div className="h-1 w-8 bg-kcd-accent"></div>
            <span className="text-[10px] tracking-[0.4em] text-kcd-accent uppercase font-sans font-bold">Package Integration Service</span>
          </div>
          <h2 className="text-4xl font-bold uppercase tracking-tight text-white">Neural <span className="text-kcd-accent">Overhaul</span> Registry</h2>
        </div>
        <button className="flex items-center gap-3 px-6 py-3 bg-kcd-accent text-kcd-bg text-[10px] font-bold uppercase tracking-widest hover:bg-white transition-all font-sans">
          <Download className="w-4 h-4" /> Synchronize All
        </button>
      </header>

      <div className="grid grid-cols-1 gap-6">
        {mods.map((mod, i) => (
          <motion.div
            key={mod.id}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.05 }}
            className={cn(
              "p-8 bg-kcd-surface border transition-all duration-300 flex items-center gap-8 group relative overflow-hidden",
              mod.status === 'Enabled' ? "border-kcd-accent/30 bg-kcd-surface shadow-[0_0_20px_rgba(193,154,77,0.05)]" : "border-kcd-border opacity-60"
            )}
          >
            {mod.aiEnhanced && (
              <div className="absolute top-0 right-0 p-1 px-4 bg-kcd-accent/10 text-kcd-accent text-[8px] font-bold uppercase tracking-[0.3em] font-sans border-b border-l border-kcd-accent/30">
                Neural Enhancement Active
              </div>
            )}

            <div className={cn(
              "w-16 h-16 bg-kcd-bg border transition-all duration-300 flex items-center justify-center flex-shrink-0",
              mod.status === 'Enabled' ? "border-kcd-accent/50 text-kcd-accent" : "border-kcd-border text-kcd-muted"
            )}>
              {mod.aiEnhanced ? <Cpu className="w-8 h-8" /> : <Settings className="w-8 h-8" />}
            </div>

            <div className="flex-1 space-y-4">
              <div className="flex items-end gap-4">
                <h4 className="text-2xl font-bold text-white tracking-tight leading-none uppercase">{mod.name}</h4>
                <span className="text-[10px] font-mono font-bold text-kcd-muted leading-none mb-1">REV_{mod.version.replace(/\./g, '_')}</span>
              </div>
              <p className="text-sm text-kcd-text/70 leading-relaxed max-w-3xl font-serif italic">"{mod.description}"</p>
              <div className="flex items-center gap-6 text-[10px] uppercase font-bold tracking-[0.2em] text-kcd-muted font-sans font-bold">
                <span className="flex items-center gap-2 transition-colors group-hover:text-kcd-accent"><Zap className="w-3 h-3" /> Source: {mod.author}</span>
                <div className="w-1 h-1 bg-kcd-border rounded-full" />
                <span className={cn(
                  "flex items-center gap-2",
                  mod.status === 'Enabled' ? "text-green-500" : "text-kcd-muted"
                )}>
                  {mod.status === 'Enabled' ? <CheckCircle className="w-3.5 h-3.5" /> : <AlertCircle className="w-3.5 h-3.5" />} 
                  Status: {mod.status}
                </span>
              </div>
            </div>

            <div className="flex items-stretch gap-3 self-stretch">
              <button 
                onClick={() => toggleMod(mod.id)}
                className={cn(
                  "px-8 flex items-center text-[10px] font-bold uppercase tracking-widest transition-all border font-sans",
                  mod.status === 'Enabled' 
                    ? "bg-kcd-accent text-kcd-bg border-kcd-accent hover:bg-white" 
                    : "bg-kcd-bg border-kcd-border text-kcd-muted hover:border-kcd-accent/50"
                )}
              >
                {mod.status === 'Enabled' ? 'Deactivate' : 'Initialize'}
              </button>
              <button className="px-4 bg-kcd-bg border border-kcd-border text-kcd-muted hover:text-red-500 hover:border-red-500/50 transition-all">
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      <footer className="p-8 bg-kcd-bg border border-kcd-border flex items-center justify-between relative overflow-hidden group">
         <div className="absolute top-0 right-0 w-24 h-full bg-kcd-accent/5 skew-x-12 translate-x-12 group-hover:translate-x-6 transition-transform duration-700" />
         
         <div className="flex items-center gap-5 relative z-10">
            <div className="p-4 bg-kcd-accent/10 border border-kcd-accent/30 text-kcd-accent">
               <Link className="w-6 h-6" />
            </div>
            <div>
               <p className="text-lg font-bold text-white uppercase tracking-tight">System Link: <span className="text-kcd-accent">Synchronized</span></p>
               <p className="text-[10px] text-kcd-muted uppercase tracking-[0.3em] font-sans font-bold">Xbox Retail Bridge Protocol v2.5 Active</p>
            </div>
         </div>
         <div className="flex gap-8 font-mono text-[10px] text-kcd-muted font-bold relative z-10">
            <div className="flex flex-col items-end">
               <span className="opacity-40 uppercase mb-1 font-sans tracking-tighter">Stack Order</span>
               <span className="text-kcd-accent">HEX_0x12_A_9</span>
            </div>
            <div className="flex flex-col items-end">
               <span className="opacity-40 uppercase mb-1 font-sans tracking-tighter">Kernel Stability</span>
               <span className="text-green-600">STATE_OPTIMAL</span>
            </div>
         </div>
      </footer>
    </div>
  );
}
